const palette = {
  background: "#f7f3ea",
  border: "#dacdb8",
  card: "#fffdf8",
  clay: "#8a4b2a",
  dangerBorder: "#efb78f",
  dangerText: "#71381f",
  dangerTitle: "#8a3f20",
  dangerWash: "#fff1e8",
  divider: "#ebe1d1",
  ink: "#1f2933",
  input: "#fffaf1",
  muted: "#56616f",
  placeholder: "#9a8d7c",
  roseBorder: "#f2c9c2",
  roseText: "#87463f",
  roseWash: "#ffe8e1",
  sage: "#256c63",
  sageBorder: "#b9d7cd",
  sageSoftBorder: "#c7d8cf",
  sageText: "#2e625b",
  sageWash: "#e4f1ea",
  skyBorder: "#bfdae7",
  skyText: "#315d71",
  skyWash: "#e5f3f7",
  subtleInk: "#46515e",
  sunBorder: "#e5d596",
  sunText: "#766421",
  sunWash: "#f6efc9",
  tan: "#7d6b57",
  track: "#e8dfcf",
} as const;

export const colors = {
  ...palette,
  action: {
    primary: palette.sage,
    primaryText: palette.card,
    secondary: palette.card,
  },
  borders: {
    default: palette.border,
    danger: palette.dangerBorder,
    divider: palette.divider,
    selected: palette.sageSoftBorder,
    success: palette.sageBorder,
  },
  feedback: {
    dangerBackground: palette.dangerWash,
    dangerText: palette.dangerText,
    dangerTitle: palette.dangerTitle,
  },
  surface: {
    app: palette.background,
    card: palette.card,
    input: palette.input,
    inverse: palette.ink,
    progressTrack: palette.track,
    successSoft: palette.sageWash,
  },
  hobby: {
    clay: {
      border: palette.dangerBorder,
      icon: palette.clay,
      surface: palette.dangerWash,
      text: palette.dangerText,
    },
    rose: {
      border: palette.roseBorder,
      icon: palette.roseText,
      surface: palette.roseWash,
      text: palette.roseText,
    },
    sage: {
      border: palette.sageBorder,
      icon: palette.sage,
      surface: palette.sageWash,
      text: palette.sageText,
    },
    sky: {
      border: palette.skyBorder,
      icon: palette.skyText,
      surface: palette.skyWash,
      text: palette.skyText,
    },
    sun: {
      border: palette.sunBorder,
      icon: palette.sunText,
      surface: palette.sunWash,
      text: palette.sunText,
    },
  },
  text: {
    accent: palette.clay,
    body: palette.subtleInk,
    brand: palette.sage,
    inverse: palette.card,
    muted: palette.muted,
    placeholder: palette.placeholder,
    primary: palette.ink,
    success: palette.sageText,
    tertiary: palette.tan,
  },
} as const;
