import type { HobbyIcon } from "@skillstep/shared";
import {
  Bike,
  BookOpen,
  BookOpenText,
  Camera,
  Car,
  Clapperboard,
  Club,
  Coffee,
  CookingPot,
  Crown,
  Dumbbell,
  Footprints,
  Gamepad2,
  Guitar,
  Languages,
  MicVocal,
  Music,
  NotebookPen,
  Palette,
  PenTool,
  PersonStanding,
  Plane,
  Sparkles,
  SportShoe,
  Sprout,
  Trophy,
  Video,
  Volleyball,
  Waves,
} from "lucide-react-native";
import type { ComponentType } from "react";

export type IconComponent = ComponentType<{
  color?: string;
  size?: number;
  strokeWidth?: number;
}>;

export const hobbyIcons: Record<HobbyIcon, IconComponent> = {
  art: Palette,
  book: BookOpen,
  camera: Camera,
  cards: Club,
  cars: Car,
  coffee: Coffee,
  content: Clapperboard,
  cooking: CookingPot,
  cycling: Bike,
  dance: Footprints,
  design: PenTool,
  fitness: Dumbbell,
  gaming: Gamepad2,
  gardening: Sprout,
  guitar: Guitar,
  language: Languages,
  music: Music,
  reading: BookOpenText,
  running: SportShoe,
  singing: MicVocal,
  sparkles: Sparkles,
  sports: Volleyball,
  strategy: Crown,
  swimming: Waves,
  tennis: Trophy,
  travel: Plane,
  video: Video,
  writing: NotebookPen,
  yoga: PersonStanding,
};
